# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20190224_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Unit',
            field=models.CharField(choices=[('eas', 'EAS'), ('analytics', 'Analytics'), ('suneralab', 'Sunera Lab')], default='eas', max_length=50),
        ),
    ]
