# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-01 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20190301_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
