# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190219_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Unit', models.CharField(choices=[(b'eas', b'EAS'), (b'analytics', b'Analytics'), (b'suneralab', b'Sunera Lab')], default=b'eas', max_length=50)),
                ('Subject', models.CharField(max_length=200)),
            ],
        ),
    ]
