# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-24 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Unit',
            new_name='unit',
        ),
    ]
