# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-24 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190224_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='unit',
            new_name='Unit',
        ),
    ]
